server:
  port: 8080

spring:
  liquibase:
    change-log: classpath:liquibase/master.xml
    enabled: true
    contexts: dev
    drop-first: false
    clear-checksums: false
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse_management
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret-key: "MWIxNzc4NDg0MjMzNDVmZGY4ZjgwZTBkMDU4ZWVjYWNiMTdkZjMwNTJhOTNmNDZiYWVmN2MyOGQyNjQ2MzdiMTc="
    expiration-time: 3600000
    refresh-expiration-time: 86400000